name: Deploy HTML to EC2
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Show All files
      run: ls -al
    - name : Doing SSH on EC2
      uses: appleboy/ssh-action@v1
      with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.USERNAME}}
          password: ${{ secrets.SSH_KEY}}
          port: 22
          script: |
            who
            pwd
            mkdir -p /tmp/test
            echo "hello world" > /tmp/test/hello.txt
            cd /tmp/test
            ls -al
