name: Deploy HTML to EC2
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Show All files
      run: ls -al
    
    - name : Doing SCP on EC2
      uses: appleboy/scp-action@v1
      with:
          host: ${{ secrets.HOSTIP }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSHKEY }}
          port: 22
          source: "./"
          target: "/home/ubuntu/"
