name: Deploy HTML to EC2
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Show All files
      run: ls -al

            
    - name : Upload HTML to EC2 temp folder
      uses: appleboy/scp-action@v1
      with:
          host: ${{ secrets.HOSTIP }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSHKEY }}
          port: 22
          source: "./*"
          target: "~/temp-html/"

      
    - name : Setup NGINX and move HTML files
      uses: appleboy/ssh-action@v1
      with:
          host: ${{ secrets.HOSTIP }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSHKEY }}
          port: 22
          script: |
            mkdir -p ~/temp-html
            sudo apt-get update -y
            sudo apt-get install nginx -y
            sudo systemctl start nginx
            sudo systemctl enable nginx
            # Print uploaded files
            echo "Checking home directory contents:"
            ls -l ~
            # Clear NGINX root and copy new files
            sudo rm -rf /var/www/html/*
            sudo cp -r ~/index.html /var/www/html/
